export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

/* Classroom */
export const CREATE_CLASSROOM = "CREATE_CLASSROOM";
export const RETRIEVE_CLASSROOM = "RETRIEVE_CLASSROOMS";
export const RETRIEVE_CLASSROOM_BY_FILTER = "RETRIEVE_CLASSROOM_BY_FILTER";
export const RETRIEVE_ALL_CLASSROOMS = "RETRIEVE_ALL_CLASSROOMS";
export const UPDATE_CLASSROOM = "UPDATE_CLASSROOM";
export const DELETE_CLASSROOM = "DELETE_CLASSROOM";

/* Sensor */
export const CREATE_SENSOR = "CREATE_SENSOR";
export const RETRIEVE_SENSOR = "RETRIEVE_SENSOR";
export const RETRIEVE_ALL_SENSORS = "RETRIEVE_ALL_SENSORS";
export const UPDATE_SENSOR = "UPDATE_SENSOR";
export const DELETE_SENSOR = "DELETE_SENSOR";

/* Sensor Values */
export const RETRIEVE_ALL_SENSOR_VALUES = "RETRIEVE_ALL_SENSOR_VALUES";
export const DELETE_SENSOR_VALUES = "DELETE_SENSOR_VALUES";